### ISSUE TITLE
Announce the idea of plugin development

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion-plugin-announcements#4]
I understand the announcement should be posted to the user's personal center of the short message, rather than paste the content on the page module.

I hope that SBR can develop short message plugins that send notifications and announcements to users, or integrate them into the current message plug-in.

**Comment by vbezruchkin** [comment]
Hello,

Thanks for your request. Yes, the idea behind this plugin should be as follows:
- administrators can easily notify their users about site changes, etc.
- these notifications should be displayed in a separate block, or directly on pages in a reserved place

This plugin is not related to a Private Messages plugin, and it should not send any notifications to a specific person. This should be done by another plugin we have - Mailer - it allows to send emails to specific groups or users directly.

Cheers

**Comment by gesonchi** [comment]
Yes. There should be a plug-in to keep the site bulletin.

There should also be a plug-in to send messages to a specified user group, which should be integrated into the current message plug-in to avoid the waste of redundant development.
