### ISSUE TITLE
Caching 1 language content

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-plugin-announcements#8]
If you have more than 1 language on your site and try to see the frontend 
you'll always see content from one language that is cached

**Comment by Chehadeej** [comment]
Dears, any update on this issue? is to going to be fixed in 4.2.2?

**Comment by 4unkur** [comment]
I've just pushed the fix. All the changes can be seen in the commit above

**Comment by Chehadeej** [comment]
Confirmed problem solved!
